[package]
name = "clock"
version = "0.1.3"
authors = ["Yung-Jin (Joey) Hu <yungjinhu@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
chrono = "0.4"
clap = "2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"