[package]
name = "serde-eg"
version = "0.1.0"
authors = ["Yung-Jin (Joey) Hu <yungjinhu@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.8"
serde_json = "1"
