[package]
name = "particles"
version = "0.1.0"
authors = ["Yung-Jin (Joey) Hu <yungjinhu@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.117.0"
piston2d-graphics = "0.39.0"
rand = "0.3"
